### ISSUE TITLE
Scrollbar is missing from code samples Chrome

### ISSUE THREAD

**Issue by BaldvinTh** [aws-amplify/aws-amplify.github.io#15]
Some code samples may have code and/or comments that extend outside the allotted container, example:
https://aws-amplify.github.io/amplify-js/media/authentication_guide#launching-the-hosted-ui

Issue seems to stem from `.docs-page-container ::-webkit-scrollbar` setting scrollbar height to 0px.

Possible solution:
```css
.docs-page-container .highlight ::-webkit-scrollbar { height: 7px; }
```

Tested in 
Chrome 69.0.3497.100

--
Firefox is not affected
